name: Find hosts

on: 
  push:
    branches:
      - master
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

env:
  STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
  MONGO_URI: ${{ secrets.MONGO_URI }}
  DB_NAME: ${{ secrets.DB_NAME }}
  LOG_DB_NAME: ${{ secrets.LOG_DB_NAME }}
  

jobs:
  pull-data:
    name: Steam Pull
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python3.12
      uses: actions/setup-python@v4 
      with:
        python-version: '3.12'
        
    - name: Check-out Repo
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: python -m pip install -r requirements.txt

    - name: Pull Data
      run: python find_servers.py
      